config/routes.rb
Rails.application.routes.draw do
  get 'similarity/index'

  get 'main' => 'similarity#index'

  root 'similarity#index'

  resources :results

end

app/models/result.rb
class Result < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/results_controller.rb
class ResultsController < ApplicationController
  before_action :set_result, only: [:show, :edit, :update, :destroy]

  # GET /results
  # GET /results.json
  def index
    @results = Result.all
  end

  # GET /results/1
  # GET /results/1.json
  def show
  end

  # GET /results/new
  def new
    @result = Result.new
  end

  # GET /results/1/edit
  def edit
  end

  # POST /results
  # POST /results.json
  def create
    @result = Result.new(result_params)

    respond_to do |format|
      if @result.save
        format.html { redirect_to @result, notice: 'Result was successfully created.' }
        format.json { render :show, status: :created, location: @result }
      else
        format.html { render :new }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /results/1
  # PATCH/PUT /results/1.json
  def update
    respond_to do |format|
      if @result.update(result_params)
        format.html { redirect_to @result, notice: 'Result was successfully updated.' }
        format.json { render :show, status: :ok, location: @result }
      else
        format.html { render :edit }
        format.json { render json: @result.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /results/1
  # DELETE /results/1.json
  def destroy
    @result.destroy
    respond_to do |format|
      format.html { redirect_to results_url, notice: 'Result was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_result
      @result = Result.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def result_params
      params.require(:result).permit(:user, :similarity)
    end
end

app/controllers/similarity_controller.rb
class SimilarityController < ApplicationController
  def index
  	@data2 = {
      labels: ["Following","Retweets","Descripción"],
      datasets: [
      {
          data: [45, 62, 38],
          labels: "@sonic_hedgehog",
          backgroundColor: ["#cd93b44","#9fbdff","#4c9cce"],
          borderColor: ["rgba(220,220,220,1)","rgba(220,220,220,1)","rgba(220,220,220,1)" ]

      }],

}

@data3 = {
labels: ["Following", "Retweets", "Descripción"],
datasets: [
{
    labels: "@lolomanolo",
    backgroundColor: ["#cd93b44","#9fbdff","#4c9cce"],
    borderColor: ["rgba(220,220,220,1)","rgba(220,220,220,1)","rgba(220,220,220,1)" ],
    data: [65, 96, 65]
}],

}

@data4 = {
labels: ["Following", "Retweets", "Descripción"],
datasets: [
{
    labels: "@mferser",
    backgroundColor: ["#cd93b44","#9fbdff","#4c9cce"],
    borderColor: ["rgba(220,220,220,1)","rgba(220,220,220,1)","rgba(220,220,220,1)" ],
    data: [45, 23, 12]
}],

}
options = {}
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/similarity_helper.rb
module SimilarityHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Twitterapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <link rel="stylesheet" type="text/css" href="http://fonts.googleapis.com/css?family=Ubuntu">
  <script src="Chart.js"></script>
</head>
<body>
<%= yield %>

</body>
</html>

app/views/results/_form.html.erb
<%= form_for(@result) do |f| %>
  <% if @result.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@result.errors.count, "error") %> prohibited this result from being saved:</h2>

      <ul>
      <% @result.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user %><br>
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :similarity %><br>
    <%= f.text_field :similarity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/results/edit.html.erb
<h1>Editing Result</h1>

<%= render 'form' %>

<%= link_to 'Show', @result %> |
<%= link_to 'Back', results_path %>

app/views/results/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Results</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Similarity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @results.each do |result| %>
      <tr>
        <td><%= result.user %></td>
        <td><%= result.similarity %></td>
        <td><%= link_to 'Show', result %></td>
        <td><%= link_to 'Edit', edit_result_path(result) %></td>
        <td><%= link_to 'Destroy', result, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Result', new_result_path %>

app/views/results/new.html.erb
<h1>New Result</h1>

<%= render 'form' %>

<%= link_to 'Back', results_path %>

app/views/results/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @result.user %>
</p>

<p>
  <strong>Similarity:</strong>
  <%= @result.similarity %>
</p>

<%= link_to 'Edit', edit_result_path(@result) %> |
<%= link_to 'Back', results_path %>

app/views/similarity/index.html.erb
	<h1>Twitter Similarity Beta</h1>
	<div class="float-box">
		<div class="top">
			<a href ="#"><img src="images/twitter-512.png"  class="aqui"></a>
			<div class="usuario-top"><a href=#>@BobRoss</a></div>
		</div>
		<div class="lateral-bar">
			<div class="list-group nav">
				<button type="button" class="list-group-item" id="butt1">DateBot</button>
				<button type="button" class="list-group-item disabled" id="butt2">Analisís en profundidad</button>
				<button type="button" class="list-group-item" id="butt3">Busqueda por usuario</button>
			</div>
		</div>

		<div class="body-content">

			<div id="siman">

			<div id="sonic" class="enablede">

				<div class="content">
					<h4>Similaridad con @sonic_hedgehog</h4>
					<%= doughnut_chart @data2 %>
				</div>


				<div class="twitt-space">
					<blockquote class="twitter-tweet" data-lang="es"><p lang="en" dir="ltr">What Aaron said. Thanks for all your support! Now, about those numbers... <a href="https://twitter.com/hashtag/sxsw?src=hash">#sxsw</a> <a href="https://twitter.com/hashtag/historyofsonic?src=hash">#historyofsonic</a></p>&mdash; Sonic the Hedgehog (@sonic_hedgehog) <a href="https://twitter.com/sonic_hedgehog/status/711299313016504320">19 de marzo de 2016</a></blockquote>
					<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>	</div>
				</div>

					<div id="mfer" class="disenablede">
						<div class="content">
							<h4>Similaridad con @mferser</h4>
							<%= doughnut_chart @data4 %>
						</div>
						<div class="twitt-space">
							<blockquote class="twitter-tweet" data-lang="es"><p lang="en" dir="ltr">January 10 2016 - David Bowie died peacefully today surrounded by his family after a courageous 18 month battle... <a href="https://t.co/ENRSiT43Zy">https://t.co/ENRSiT43Zy</a></p>&mdash; David Bowie Official (@DavidBowieReal) <a href="https://twitter.com/DavidBowieReal/status/686434952464982016">11 de enero de 2016</a></blockquote>
		<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script></div>

					</div>

				<button type="button" class="btn btn-default btn-sm next-but-esp" id="change-context">Siguiente</button>
			</div>


			<div id="datebot">
				<div class="chat">

					<div class="panel panel-default">
						<div class="panel-body">
							<div class="row">
								<div class="col-xs-2">
									<a href="#" class="thumbnail">
										<img src="..." alt="...">
									</a>
								</div>
								<div class="col-md-9">
									Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed eiusmod tempor incidunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquid ex ea commodi consequat.
								</div>
							</div>
						</div>
						<div class="panel-footer">DateBot</div>

						<div class="panel panel-default">
							<div class="panel-body">
								<div class="row">
									<div class="col-md-9">
										Quis aute iure reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint obcaecat cupiditat non proident, sunt in culpa qui officia deserunt mollit anim id est
									</div>
									<div class="col-xs-2">
										<a href="#" class="thumbnail">
											<img src="..." alt="...">
										</a>
									</div>
								</div>
							</div>
							<div class="panel-footer">@usuario</div>
						</div>
					</div>

					<div class="input-group">
						<input type="text" class="form-control dlineblock" placeholder="Escribe tu mensaje" aria-describedby="basic-addon1">
						<button type="button" class="btn btn-default btn-sm dlineblock">Enviar</button>
					</div>


				</div>
			</div>

			<div id="deepse">
				<div id="result">
					<div class="content">
						<h4>Similaridad con @lolomanolo</h4>
						<%= doughnut_chart @data3 %>
					</div>


					<div class="twitt-space">
						<blockquote class="twitter-tweet" data-cards="hidden" data-lang="es"><p lang="es" dir="ltr"><a href="https://twitter.com/hashtag/Usach?src=hash">#Usach</a> tendrá triestamentalidad con derecho a voz y <a href="https://twitter.com/hashtag/voto?src=hash">#voto</a> de estudiantes y trabajadores <a href="https://t.co/khm9z2uEbJ">https://t.co/khm9z2uEbJ</a></p>&mdash; el mostrador (@elmostrador) <a href="https://twitter.com/elmostrador/status/687363605977788416">13 de enero de 2016</a></blockquote>
						<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
					</div>

					<script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
				</div>

				<div id="butsearch">
					<div class="input-group">
						<input type="text" class="form-control dlineblock" placeholder="Escribe el nombre de usuario" aria-describedby="basic-addon1">
						<button type="button" class="btn btn-default btn-sm" id="sebott">Buscar</button>
					</div>
				</div>

</div>




			</div>
		</div>